import Foundation

struct TimeZoneData {
    static let allTimezones = [
        // North America
        City(code: "NYC", timeZoneIdentifier: "America/New_York", displayName: "New York", emoji: "🗽"),
        City(code: "LAX", timeZoneIdentifier: "America/Los_Angeles", displayName: "Los Angeles", emoji: "🌴"),
        City(code: "CHI", timeZoneIdentifier: "America/Chicago", displayName: "Chicago", emoji: "🏙️"),
        City(code: "DEN", timeZoneIdentifier: "America/Denver", displayName: "Denver", emoji: "🏔️"),
        City(code: "PHX", timeZoneIdentifier: "America/Phoenix", displayName: "Phoenix", emoji: "🌵"),
        City(code: "LAS", timeZoneIdentifier: "America/Los_Angeles", displayName: "Las Vegas", emoji: "🎰"),
        City(code: "SEA", timeZoneIdentifier: "America/Los_Angeles", displayName: "Seattle", emoji: "🌲"),
        City(code: "MIA", timeZoneIdentifier: "America/New_York", displayName: "Miami", emoji: "🏖️"),
        City(code: "ATL", timeZoneIdentifier: "America/New_York", displayName: "Atlanta", emoji: "🍑"),
        City(code: "BOS", timeZoneIdentifier: "America/New_York", displayName: "Boston", emoji: "🦞"),
        City(code: "YVR", timeZoneIdentifier: "America/Vancouver", displayName: "Vancouver", emoji: "🇨🇦"),
        City(code: "YYZ", timeZoneIdentifier: "America/Toronto", displayName: "Toronto", emoji: "🇨🇦"),
        City(code: "YOW", timeZoneIdentifier: "America/Toronto", displayName: "Ottawa", emoji: "🇨🇦"),
        City(code: "MEX", timeZoneIdentifier: "America/Mexico_City", displayName: "Mexico City", emoji: "🇲🇽"),
        
        // South America
        City(code: "GRU", timeZoneIdentifier: "America/Sao_Paulo", displayName: "São Paulo", emoji: "🇧🇷"),
        City(code: "GIG", timeZoneIdentifier: "America/Sao_Paulo", displayName: "Rio de Janeiro", emoji: "🇧🇷"),
        City(code: "BSB", timeZoneIdentifier: "America/Sao_Paulo", displayName: "Brasília", emoji: "🇧🇷"),
        City(code: "EZE", timeZoneIdentifier: "America/Argentina/Buenos_Aires", displayName: "Buenos Aires", emoji: "🇦🇷"),
        City(code: "SCL", timeZoneIdentifier: "America/Santiago", displayName: "Santiago", emoji: "🇨🇱"),
        City(code: "LIM", timeZoneIdentifier: "America/Lima", displayName: "Lima", emoji: "🇵🇪"),
        City(code: "BOG", timeZoneIdentifier: "America/Bogota", displayName: "Bogotá", emoji: "🇨🇴"),
        City(code: "CCS", timeZoneIdentifier: "America/Caracas", displayName: "Caracas", emoji: "🇻🇪"),
        
        // Europe
        City(code: "LHR", timeZoneIdentifier: "Europe/London", displayName: "London", emoji: "🇬🇧"),
        City(code: "CDG", timeZoneIdentifier: "Europe/Paris", displayName: "Paris", emoji: "🇫🇷"),
        City(code: "FRA", timeZoneIdentifier: "Europe/Berlin", displayName: "Frankfurt", emoji: "🇩🇪"),
        City(code: "BER", timeZoneIdentifier: "Europe/Berlin", displayName: "Berlin", emoji: "🇩🇪"),
        City(code: "MUC", timeZoneIdentifier: "Europe/Berlin", displayName: "Munich", emoji: "🇩🇪"),
        City(code: "AMS", timeZoneIdentifier: "Europe/Amsterdam", displayName: "Amsterdam", emoji: "🇳🇱"),
        City(code: "BRU", timeZoneIdentifier: "Europe/Brussels", displayName: "Brussels", emoji: "🇧🇪"),
        City(code: "ZUR", timeZoneIdentifier: "Europe/Zurich", displayName: "Zurich", emoji: "🇨🇭"),
        City(code: "VIE", timeZoneIdentifier: "Europe/Vienna", displayName: "Vienna", emoji: "🇦🇹"),
        City(code: "FCO", timeZoneIdentifier: "Europe/Rome", displayName: "Rome", emoji: "🇮🇹"),
        City(code: "MXP", timeZoneIdentifier: "Europe/Rome", displayName: "Milan", emoji: "🇮🇹"),
        City(code: "MAD", timeZoneIdentifier: "Europe/Madrid", displayName: "Madrid", emoji: "🇪🇸"),
        City(code: "BCN", timeZoneIdentifier: "Europe/Madrid", displayName: "Barcelona", emoji: "🇪🇸"),
        City(code: "LIS", timeZoneIdentifier: "Europe/Lisbon", displayName: "Lisbon", emoji: "🇵🇹"),
        City(code: "ARN", timeZoneIdentifier: "Europe/Stockholm", displayName: "Stockholm", emoji: "🇸🇪"),
        City(code: "CPH", timeZoneIdentifier: "Europe/Copenhagen", displayName: "Copenhagen", emoji: "🇩🇰"),
        City(code: "OSL", timeZoneIdentifier: "Europe/Oslo", displayName: "Oslo", emoji: "🇳🇴"),
        City(code: "HEL", timeZoneIdentifier: "Europe/Helsinki", displayName: "Helsinki", emoji: "🇫🇮"),
        City(code: "SVO", timeZoneIdentifier: "Europe/Moscow", displayName: "Moscow", emoji: "🇷🇺"),
        City(code: "WAW", timeZoneIdentifier: "Europe/Warsaw", displayName: "Warsaw", emoji: "🇵🇱"),
        City(code: "PRG", timeZoneIdentifier: "Europe/Prague", displayName: "Prague", emoji: "🇨🇿"),
        City(code: "BUD", timeZoneIdentifier: "Europe/Budapest", displayName: "Budapest", emoji: "🇭🇺"),
        City(code: "ATH", timeZoneIdentifier: "Europe/Athens", displayName: "Athens", emoji: "🇬🇷"),
        City(code: "IST", timeZoneIdentifier: "Europe/Istanbul", displayName: "Istanbul", emoji: "🇹🇷"),
        
        // Asia
        City(code: "NRT", timeZoneIdentifier: "Asia/Tokyo", displayName: "Tokyo", emoji: "🇯🇵"),
        City(code: "KIX", timeZoneIdentifier: "Asia/Tokyo", displayName: "Osaka", emoji: "🇯🇵"),
        City(code: "ICN", timeZoneIdentifier: "Asia/Seoul", displayName: "Seoul", emoji: "🇰🇷"),
        City(code: "PEK", timeZoneIdentifier: "Asia/Shanghai", displayName: "Beijing", emoji: "🇨🇳"),
        City(code: "PVG", timeZoneIdentifier: "Asia/Shanghai", displayName: "Shanghai", emoji: "🇨🇳"),
        City(code: "CAN", timeZoneIdentifier: "Asia/Shanghai", displayName: "Guangzhou", emoji: "🇨🇳"),
        City(code: "HKG", timeZoneIdentifier: "Asia/Hong_Kong", displayName: "Hong Kong", emoji: "🇭🇰"),
        City(code: "TPE", timeZoneIdentifier: "Asia/Taipei", displayName: "Taipei", emoji: "🇹🇼"),
        City(code: "SIN", timeZoneIdentifier: "Asia/Singapore", displayName: "Singapore", emoji: "🇸🇬"),
        City(code: "BKK", timeZoneIdentifier: "Asia/Bangkok", displayName: "Bangkok", emoji: "🇹🇭"),
        City(code: "CGK", timeZoneIdentifier: "Asia/Jakarta", displayName: "Jakarta", emoji: "🇮🇩"),
        City(code: "KUL", timeZoneIdentifier: "Asia/Kuala_Lumpur", displayName: "Kuala Lumpur", emoji: "🇲🇾"),
        City(code: "MNL", timeZoneIdentifier: "Asia/Manila", displayName: "Manila", emoji: "🇵🇭"),
        City(code: "HAN", timeZoneIdentifier: "Asia/Ho_Chi_Minh", displayName: "Hanoi", emoji: "🇻🇳"),
        City(code: "SGN", timeZoneIdentifier: "Asia/Ho_Chi_Minh", displayName: "Ho Chi Minh City", emoji: "🇻🇳"),
        City(code: "BOM", timeZoneIdentifier: "Asia/Kolkata", displayName: "Mumbai", emoji: "🇮🇳"),
        City(code: "DEL", timeZoneIdentifier: "Asia/Kolkata", displayName: "New Delhi", emoji: "🇮🇳"),
        City(code: "BLR", timeZoneIdentifier: "Asia/Kolkata", displayName: "Bangalore", emoji: "🇮🇳"),
        City(code: "MAA", timeZoneIdentifier: "Asia/Kolkata", displayName: "Chennai", emoji: "🇮🇳"),
        City(code: "CCU", timeZoneIdentifier: "Asia/Kolkata", displayName: "Kolkata", emoji: "🇮🇳"),
        City(code: "ISB", timeZoneIdentifier: "Asia/Karachi", displayName: "Islamabad", emoji: "🇵🇰"),
        City(code: "KHI", timeZoneIdentifier: "Asia/Karachi", displayName: "Karachi", emoji: "🇵🇰"),
        City(code: "DAC", timeZoneIdentifier: "Asia/Dhaka", displayName: "Dhaka", emoji: "🇧🇩"),
        City(code: "CMB", timeZoneIdentifier: "Asia/Colombo", displayName: "Colombo", emoji: "🇱🇰"),
        City(code: "RGN", timeZoneIdentifier: "Asia/Yangon", displayName: "Yangon", emoji: "🇲🇲"),
        City(code: "DXB", timeZoneIdentifier: "Asia/Dubai", displayName: "Dubai", emoji: "🇦🇪"),
        City(code: "DOH", timeZoneIdentifier: "Asia/Qatar", displayName: "Doha", emoji: "🇶🇦"),
        City(code: "KWI", timeZoneIdentifier: "Asia/Kuwait", displayName: "Kuwait City", emoji: "🇰🇼"),
        City(code: "RUH", timeZoneIdentifier: "Asia/Riyadh", displayName: "Riyadh", emoji: "🇸🇦"),
        City(code: "TLV", timeZoneIdentifier: "Asia/Jerusalem", displayName: "Tel Aviv", emoji: "🇮🇱"),
        City(code: "AMM", timeZoneIdentifier: "Asia/Amman", displayName: "Amman", emoji: "🇯🇴"),
        City(code: "BEY", timeZoneIdentifier: "Asia/Beirut", displayName: "Beirut", emoji: "🇱🇧"),
        City(code: "BAH", timeZoneIdentifier: "Asia/Bahrain", displayName: "Manama", emoji: "🇧🇭"),
        City(code: "MCT", timeZoneIdentifier: "Asia/Muscat", displayName: "Muscat", emoji: "🇴🇲"),
        City(code: "IKA", timeZoneIdentifier: "Asia/Tehran", displayName: "Tehran", emoji: "🇮🇷"),
        City(code: "KBL", timeZoneIdentifier: "Asia/Kabul", displayName: "Kabul", emoji: "🇦🇫"),
        City(code: "TAS", timeZoneIdentifier: "Asia/Tashkent", displayName: "Tashkent", emoji: "🇺🇿"),
        City(code: "ALA", timeZoneIdentifier: "Asia/Almaty", displayName: "Almaty", emoji: "🇰🇿"),
        
        // Africa
        City(code: "CAI", timeZoneIdentifier: "Africa/Cairo", displayName: "Cairo", emoji: "🇪🇬"),
        City(code: "JNB", timeZoneIdentifier: "Africa/Johannesburg", displayName: "Johannesburg", emoji: "🇿🇦"),
        City(code: "CPT", timeZoneIdentifier: "Africa/Johannesburg", displayName: "Cape Town", emoji: "🇿🇦"),
        City(code: "LOS", timeZoneIdentifier: "Africa/Lagos", displayName: "Lagos", emoji: "🇳🇬"),
        City(code: "ABV", timeZoneIdentifier: "Africa/Lagos", displayName: "Abuja", emoji: "🇳🇬"),
        City(code: "ACC", timeZoneIdentifier: "Africa/Accra", displayName: "Accra", emoji: "🇬🇭"),
        City(code: "ABJ", timeZoneIdentifier: "Africa/Abidjan", displayName: "Abidjan", emoji: "🇨🇮"),
        City(code: "DKR", timeZoneIdentifier: "Africa/Dakar", displayName: "Dakar", emoji: "🇸🇳"),
        City(code: "CMN", timeZoneIdentifier: "Africa/Casablanca", displayName: "Casablanca", emoji: "🇲🇦"),
        City(code: "ALG", timeZoneIdentifier: "Africa/Algiers", displayName: "Algiers", emoji: "🇩🇿"),
        City(code: "TUN", timeZoneIdentifier: "Africa/Tunis", displayName: "Tunis", emoji: "🇹🇳"),
        City(code: "LBV", timeZoneIdentifier: "Africa/Libreville", displayName: "Libreville", emoji: "🇬🇦"),
        City(code: "KIN", timeZoneIdentifier: "Africa/Kinshasa", displayName: "Kinshasa", emoji: "🇨🇩"),
        City(code: "LUA", timeZoneIdentifier: "Africa/Luanda", displayName: "Luanda", emoji: "🇦🇴"),
        City(code: "ADD", timeZoneIdentifier: "Africa/Addis_Ababa", displayName: "Addis Ababa", emoji: "🇪🇹"),
        City(code: "NBO", timeZoneIdentifier: "Africa/Nairobi", displayName: "Nairobi", emoji: "🇰🇪"),
        City(code: "DAR", timeZoneIdentifier: "Africa/Dar_es_Salaam", displayName: "Dar es Salaam", emoji: "🇹🇿"),
        City(code: "KGL", timeZoneIdentifier: "Africa/Kigali", displayName: "Kigali", emoji: "🇷🇼"),
        City(code: "KMP", timeZoneIdentifier: "Africa/Kampala", displayName: "Kampala", emoji: "🇺🇬"),
        
        // Oceania
        City(code: "SYD", timeZoneIdentifier: "Australia/Sydney", displayName: "Sydney", emoji: "🇦🇺"),
        City(code: "MEL", timeZoneIdentifier: "Australia/Melbourne", displayName: "Melbourne", emoji: "🇦🇺"),
        City(code: "BNE", timeZoneIdentifier: "Australia/Brisbane", displayName: "Brisbane", emoji: "🇦🇺"),
        City(code: "PER", timeZoneIdentifier: "Australia/Perth", displayName: "Perth", emoji: "🇦🇺"),
        City(code: "ADL", timeZoneIdentifier: "Australia/Adelaide", displayName: "Adelaide", emoji: "🇦🇺"),
        City(code: "CBR", timeZoneIdentifier: "Australia/Sydney", displayName: "Canberra", emoji: "🇦🇺"),
        City(code: "AKL", timeZoneIdentifier: "Pacific/Auckland", displayName: "Auckland", emoji: "🇳🇿"),
        City(code: "WLG", timeZoneIdentifier: "Pacific/Auckland", displayName: "Wellington", emoji: "🇳🇿"),
        City(code: "CHC", timeZoneIdentifier: "Pacific/Auckland", displayName: "Christchurch", emoji: "🇳🇿"),
        City(code: "NOU", timeZoneIdentifier: "Pacific/Noumea", displayName: "Nouméa", emoji: "🇳🇨"),
        City(code: "PPT", timeZoneIdentifier: "Pacific/Tahiti", displayName: "Papeete", emoji: "🇵🇫"),
        City(code: "HNL", timeZoneIdentifier: "Pacific/Honolulu", displayName: "Honolulu", emoji: "🏝️"),
        City(code: "ANC", timeZoneIdentifier: "America/Anchorage", displayName: "Anchorage", emoji: "🐻"),
        
        // Additional Major Cities
        City(code: "REK", timeZoneIdentifier: "Atlantic/Reykjavik", displayName: "Reykjavik", emoji: "🇮🇸"),
        City(code: "TIP", timeZoneIdentifier: "Africa/Tripoli", displayName: "Tripoli", emoji: "🇱🇾"),
        City(code: "KHR", timeZoneIdentifier: "Africa/Khartoum", displayName: "Khartoum", emoji: "🇸🇩"),
        City(code: "MPM", timeZoneIdentifier: "Africa/Maputo", displayName: "Maputo", emoji: "🇲🇿"),
        City(code: "LUS", timeZoneIdentifier: "Africa/Lusaka", displayName: "Lusaka", emoji: "🇿🇲"),
        City(code: "HRE", timeZoneIdentifier: "Africa/Harare", displayName: "Harare", emoji: "🇿🇼"),
        City(code: "GBE", timeZoneIdentifier: "Africa/Gaborone", displayName: "Gaborone", emoji: "🇧🇼"),
        City(code: "MRU", timeZoneIdentifier: "Indian/Mauritius", displayName: "Port Louis", emoji: "🇲🇺"),
        City(code: "TNR", timeZoneIdentifier: "Indian/Antananarivo", displayName: "Antananarivo", emoji: "🇲🇬"),
        City(code: "SEZ", timeZoneIdentifier: "Indian/Mahe", displayName: "Victoria", emoji: "🇸🇨"),
        City(code: "MLE", timeZoneIdentifier: "Indian/Maldives", displayName: "Malé", emoji: "🇲🇻"),
        City(code: "ULN", timeZoneIdentifier: "Asia/Ulaanbaatar", displayName: "Ulaanbaatar", emoji: "🇲🇳"),
        City(code: "PNH", timeZoneIdentifier: "Asia/Phnom_Penh", displayName: "Phnom Penh", emoji: "🇰🇭"),
        City(code: "VTE", timeZoneIdentifier: "Asia/Vientiane", displayName: "Vientiane", emoji: "🇱🇦"),
        City(code: "BWN", timeZoneIdentifier: "Asia/Brunei", displayName: "Bandar Seri Begawan", emoji: "🇧🇳"),
        City(code: "DLD", timeZoneIdentifier: "Asia/Dili", displayName: "Dili", emoji: "🇹🇱"),
        City(code: "POM", timeZoneIdentifier: "Pacific/Port_Moresby", displayName: "Port Moresby", emoji: "🇵🇬"),
        City(code: "SUV", timeZoneIdentifier: "Pacific/Fiji", displayName: "Suva", emoji: "🇫🇯"),
        City(code: "APW", timeZoneIdentifier: "Pacific/Apia", displayName: "Apia", emoji: "🇼🇸"),
        City(code: "NUK", timeZoneIdentifier: "Pacific/Tongatapu", displayName: "Nuku'alofa", emoji: "🇹🇴"),
        City(code: "TRW", timeZoneIdentifier: "Pacific/Funafuti", displayName: "Funafuti", emoji: "🇹🇻"),
        City(code: "MAJ", timeZoneIdentifier: "Pacific/Majuro", displayName: "Majuro", emoji: "🇲🇭"),
        City(code: "YAP", timeZoneIdentifier: "Pacific/Chuuk", displayName: "Chuuk", emoji: "🇫🇲"),
        City(code: "KOR", timeZoneIdentifier: "Pacific/Palau", displayName: "Koror", emoji: "🇵🇼"),
        City(code: "YRN", timeZoneIdentifier: "Pacific/Nauru", displayName: "Yaren", emoji: "🇳🇷"),
        City(code: "TRV", timeZoneIdentifier: "Pacific/Tarawa", displayName: "Tarawa", emoji: "🇰🇮")
    ]
}